### ISSUE TITLE
The reason using fp16 on pc hardware?

### ISSUE THREAD

**Issue by Klanly** [nihui/waifu2x-ncnn-vulkan#29]
Vulkan compatibility? ( I skimmed here: github.com/KhronosGroup/Vulkan-Docs/issues/706 , it says it's not a native data format for vulkan )

Saving VRAM? ( I think they will convert back to fp32 in vram, or even worse 1.5x bigger )

Here's my caffe2ncnn and a bat to convert w2x-caffe model binaries:
https://mega.nz/#!b6Zk1YjQ!KPHRIzdy-ZKvi5FoICwY65bXAx_u9Y2XYxjBev-4dxU

Also can you give me some hints where do I have to patch, to make this work in fp32?

**Comment by nihui** [comment]
the ncnn inference framework will check the hardware compability and enable fp16 automatically only if it is reported as supported, or fallback to fp32 mode otherwise. So it should work on all devices.

When fp16 is used, all model data, input and output image and intermediate blobs will be stored in fp16 mode, which saves lots of VRAM.

In general, you don't have to generate fp32 model binaries, the current fp16 model works out of box.
