### ISSUE TITLE
[bug] upconv_7_anime_style_art_rgb scale 1x not supported

### ISSUE THREAD

**Issue by aka-katto** [nihui/waifu2x-ncnn-vulkan#33]
I wasn't sure if this is a known bug or not, but vulkan is missing the files for 1x on the upconv_7_anime_style_art_rgb model. I checked and the model is missing the bin's required for 1x.

**Comment by nihui** [comment]
That's because the original caffe model didn't exist.
If you check the original waifu2x project, the scale 1x models are linked to older vgg models.
This means that there are actually no upconv7 models, but instead borrowed the vgg models.

https://github.com/nagadomi/waifu2x/tree/master/models/upconv_7/art
