### ISSUE TITLE
Output image is completely black

### ISSUE THREAD

**Issue by OrakMoya** [nihui/waifu2x-ncnn-vulkan#71]
Using arch linux with kernel 5.6.8 and an nvidia GeForce GTX 1060 6GB with driver version 440.82, and the program installed through the AUR, whenever I try to upscale an image the output is completely black. The program with the verbose tag reports no errors.

**Comment by dunnousername** [comment]
I'm having this issue too. I compiled the program from source using the latest git, and am using the exact same nvidia driver version, this time with a Quadro P620. This was on a fresh install of Fedora 32 x86_64, with kernel version 5.6.6. The input image is a 480x480 .png.

**Comment by nihui** [comment]
DO not use the ncnn master branch as it is unstable usually
https://github.com/Tencent/ncnn/tree/20200413 should be fine

**Comment by dunnousername** [comment]
Using that branch leads to an error; see https://gist.github.com/dunnousername/b2dd727137b956c2017a88a03ea73df1
I think it might be an error with ncnn, because in that ncnn version the `Pipeline` type is only defined when NCNN_VULKAN is defined as 1. I tried using CPPFLAGS=-DNCNN_VULKAN=1 in the compilation of ncnn, but it didn't change anything.

**Comment by nihui** [comment]
ncnn is now included as a submodule
From now on, waifu2x-ncnn-vulkan could always be build with the right ncnn version
