### ISSUE TITLE
Cannot use exe outside the exe's current working directory

### ISSUE THREAD

**Issue by bajuwa** [nihui/waifu2x-ncnn-vulkan#80]
Whenever I try to call the exe from outside it's current folder, it fails silently (ie doesn't print anything to the console and does not produce the expected result images)

This happens when trying to access the exe via full path:
`C:/path/to/vulkan/waifu2x-ncnn-vulkan.exe -i C:/path/to/input/ -o  C:/path/to/output/ -n 2 -s 1`

it also happens when `C:/path/to/vulkan/` is added to the path and subsequently called via:
`waifu2x-ncnn-vulkan.exe -i C:/path/to/input/ -o  C:/path/to/output/ -n 2 -s 1`

Using the exact same command arguments but from the exes folder it will work with this command:
`./waifu2x-ncnn-vulkan.exe -i C:/path/to/input/ -o  C:/path/to/output/ -n 2 -s 1`

**Comment by slashbeast** [comment]
This is because of this line https://github.com/nihui/waifu2x-ncnn-vulkan/blob/master/src/main.cpp#L378

It looks for the model files in the current working directory, does not do any lookup for where the binary is stored, in Gentoo we change it to /usr/share/waifu2x-ncnn-vulkan/ so it can work from anywhere.

**Comment by nihui** [comment]
resolved in https://github.com/nihui/waifu2x-ncnn-vulkan/commit/7db4dbb763cff777fdc1af50a058bfdf35cc5af3
