### ISSUE TITLE
how to use it from dir to dir in ubuntu?

### ISSUE THREAD

**Issue by splinter21** [nihui/waifu2x-ncnn-vulkan#90]
./waifu2x-ncnn-vulkan -i '/a/b/input/' -o '/a/b/output/' -n 3 -s 1 -g 0 -j 4:4:4

it doesn't work.

is there any demo cmd? Thanks!

**Comment by Nova-Aurora** [comment]
Does it output any error messages or just fail silently?

**Comment by SergeyLatyshev** [comment]
Try double quotes: " ".

**Comment by happyeggchen** [comment]
hi,, i met this problem what ever i  input, it just output <br>
Usage: ./waifu2x [image] [outputpng] [noise=-1/0/1/2/3] [scale=1/2] [tilesize=400]
<br>

in console

[debian buster] installed waifu2x by snap

**Comment by Nova-Aurora** [comment]
Is that waifu2x-ncnn-vulkan or some other waifu2x? You say it's installed by snap yet you're using a ./ as if you're using a binary inside a directory. Also that usage looks... off the waifu2x-ncnn-vulkan usage output looks like:

Usage: waifu2x-ncnn-vulkan -i infile -o outfile [options]...

  -h                   show this help
  -v                   verbose output
  -i input-path        input image path (jpg/png/webp) or directory
  -o output-path       output image path (jpg/png/webp) or directory
  -n noise-level       denoise level (-1/0/1/2/3, default=0)
  -s scale             upscale ratio (1/2, default=2)
  -t tile-size         tile size (>=32/0=auto, default=0) can be 0,0,0 for multi-gpu
  -m model-path        waifu2x model path (default=models-cunet)
  -g gpu-id            gpu device to use (default=0) can be 0,1,2 for multi-gpu
  -j load:proc:save    thread count for load/proc/save (default=1:2:2) can be 1:2,2,2:2 for multi-gpu
  -x                   enable tta mode
  -f format            output image format (jpg/png/webp, default=ext/png)

try running the command 'waifu2x-ncnn-vulkan' rather than ./waifu2x. I also wouldn't recommend using the snap version because it hasn't been updated since April 2019.

**Comment by happyeggchen** [comment]
Ah , alright.It solved my problem,the snap package is too old.After update to the newest version,it works perfectly
